### ISSUE TITLE
Fail on missing attributes

### ISSUE THREAD

**Issue by aslakhellesoy** [spullara/mustache.java#1]
We just switched from Velocity to Mustache because we wanted a template engine that throws errors when a template refers to variables that don't exist.

It turns out that Mustache.java doesn't do this either (it just logs). Would you accept a patch for this? Would it be against the Mustache spec? Alternatively we could make this strict behaviour configurable.

**Comment by ebuildy** [comment]
This is a very good question, how can we implement a more generic solution? 

I did something by overriding the "GuardedBinding" 👍 

```
protected synchronized Wrapper getWrapper(String name, List<Object> scopes) {
        final Wrapper foundWrapper = super.getWrapper(name, scopes);

        if (foundWrapper instanceof MissingWrapper) {
            throw new IllegalStateException(String.format("'%s' is missing!", name));
        }

        return foundWrapper;
    }
```

It works, is it the good way?

**Comment by ostronaut** [comment]
Why this issue was closed? Does mustache.java now provide some may/interface to handle missing key situation?
