### ISSUE TITLE
Support Java Optionals

### ISSUE THREAD

**Issue by eirslett** [spullara/mustache.java#108]
Java 8 introduced Optional, which saves you from NullPointerExceptions being thrown everywhere. If an Optional type is detected, could it be treated as truthy when present, falsy when absent, and, if present, its value used in the rendering? So the semantics of present would be the same as a normal value, and absent would be the same as `null`.

Java pseudocode:
```
List(
  Person(name="Jane",age=Present(34),city=Absent),
  Person(name="Adam",age=Absent,city=Some("Berlin")
)
```
Mustache:
```
{{#person}}
  = Person =
  Name: {{name}}
  Age: {{age}}
  City: {{#city}}.{{/city}}{{^city}}unknown{{/city}}
{{/person}}
```
Result:
```
= Person =
Name: Jane
Age: 34
City: unknown
= Person =
Name: Adam
Age:
City: Berlin
```

**Comment by spullara** [comment]
Added support for Optional.
