### ISSUE TITLE
Read file without specifying charset?

### ISSUE THREAD

**Issue by freewind** [spullara/mustache.java#120]
I found some code reading files without specifying charset:

```
new FileInputStream(file)
```

When my OS charset is "ASCII" and my data is Chinese, the rendered content will be partially lost.

Refer: 

https://github.com/spullara/mustache.java/blob/28bab527f3e4149b858d8bc726100fe5e41516a4/compiler/src/main/java/com/github/mustachejava/FallbackMustacheFactory.java#L106

https://github.com/spullara/mustache.java/blob/f8e148f09bc5e9035ea32ee30c7a2adaeddc4f23/compiler/src/main/java/com/github/mustachejava/resolver/FileSystemResolver.java#L52

**Comment by spullara** [comment]
Thanks, will clean this up. Need to have this linted in the build...

**Comment by spullara** [comment]
Actually, in both these cases, it is then wrapped in a BufferReader that has the character set to UTF-8.

**Comment by freewind** [comment]
You are right, the problem should not be here. But my problem exists, I will update it when I find something

**Comment by spullara** [comment]
My guess is that your files are not UTF-8 but instead are in a chinese charset. We could add an API that allows for you to specify a charset for templates but I highly suggest you switch to using UTF8. Much easier to keep things straight especially if you end up supporting multiple languages. Another possibility is to convert them during the build process. There may be aMaven plugin for that when copying them to resources.  Sam   

---Sent from Boxer | http://getboxer.com

On January 8, 2015 at 11:47:42 PM PST, freewind <notifications@github.com> wrote:You are right, the problem should not be here. But my problem exists, I will update it when I find something  —Reply to this email directly or view it on GitHub.

**Comment by freewind** [comment]
There is no Chinese characters in the template, instead, the Chinese content are injected to the variables. I can see the charset of the template is UTF-8 in IDEA, but it's strange when I use command:

     file -I test.mustache

It prints:

> test.mustache: text/html; charset=us-ascii

The content of `test.mustache` is:

```html
<html>
<head></head>
<body>
Hello, {{name}}
</body>
</html>

```

**Comment by spullara** [comment]
The file command just looks at the content and gives you the narrowest
answer. Since there are no UTF-8 characters in the file it assumes it is
ASCII.

If the chinese content is injected into the variables it should just work
since we use a Writer to write them — Twitter uses this system for many,
many languages. Do you have a unit test that breaks for me to help debug?

Sam
