### ISSUE TITLE
sbt cannot use mustache.java

### ISSUE THREAD

**Issue by eirslett** [spullara/mustache.java#123]
This is a limitation from Ivy. Look here: http://www.scala-sbt.org/0.13/docs/Library-Management.html#Known+limitations

> Specifying relativePath in the parent section of a POM will produce an error.

When I try to add the mustache compiler as a dependency in sbt, it complains about the URL not being hierarchical. (I'm on Windows 7 x64, not sure if that's a problem)

I'm not sure if there is a solution to this that doesn't involve removing the relativePath attribute...

**Comment by spullara** [comment]
It doesn't look like relativePath is necessary. I've checked in a change to remove it. Are you going to be using the Java 8 or Java 7 version?

**Comment by eirslett** [comment]
Java 7. Trying to use this as part of Zipkin, which must be able to run on java 7 runtime :-)

**Comment by spullara** [comment]
I'll do a little backporting and publish a new 0.8 that is 7 compatible. 

---Sent from Boxer | http://getboxer.com

On January 12, 2015 at 12:00:05 PM PST, Eirik Sletteberg <notifications@github.com> wrote:Java 7. Trying to use this as part of Zipkin, which must be able to run on java 7 runtime :-)     > Den 12. jan. 2015 kl. 20.02 skrev Sam Pullara <notifications@github.com>:  >  > It doesn't look like relativePath is necessary. I've checked in a change to remove it. Are you going to be using the Java 8 or Java 7 version?  >  > —  > Reply to this email directly or view it on GitHub.  > —Reply to this email directly or view it on GitHub.
