### ISSUE TITLE
Compile Mustache using Java 7?

### ISSUE THREAD

**Issue by melvinma** [spullara/mustache.java#124]
Hi, there. I got the following exception (bottom, stack trace). Presumably, this is caused by compiling classes using Java 8 instead of Java 7 and it generated a compatibility when running using Java 7. 

Here is how I got mustache. Thanks.

		<dependency>
		  <groupId>com.github.spullara.mustache.java</groupId>
		  <artifactId>compiler</artifactId>
		  <version>0.9.0</version>
		</dependency>

[INFO] java.lang.UnsupportedClassVersionError: com/github/mustachejava/MustacheFactory : Unsupported major.minor version 52.0
[INFO] 	at java.lang.ClassLoader.defineClass1(Native Method)
[INFO] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:792)
[INFO] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[INFO] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
[INFO] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
[INFO] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[INFO] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
[INFO] 	at java.security.AccessController.doPrivileged(Native Method)
[INFO] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
[INFO] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[INFO] 	at com.google.appengine.tools.development.IsolatedAppClassLoader.loadClass(IsolatedAppClassLoader.java:216)

**Comment by talios** [comment]
The README says that 0.9.0 is now Java 8 only. @spullara that's quite a harsh change for a point release isn't it?

Looks like a good change tho - and a good call since Java 7 is EOL in less than 2 months.

**Comment by spullara** [comment]
It is a harsh change though I will maintain the 0.8.x branch indefinitely as Java 6/7 compatible. I will update the README to direct non-Java 8 users to right version.

**Comment by talios** [comment]
Good call for the README tweak.

I think what makes it more harsh is that it just "appeared", https://github.com/spullara/mustache.java/commit/f8e148f09bc5e9035ea32ee30c7a2adaeddc4f23 was pushed late last december but since there was no issue raised for it - if you wern't watching the commits directly it wasn't visible.

**Comment by spullara** [comment]
I've updated the README to point to the latest 0.8 version for Java 6/7 support. There was an issue but it was somewhat hidden: https://github.com/spullara/mustache.java/issues/108
