### ISSUE TITLE
Maven Artifacts are not valid OSGi bundles

### ISSUE THREAD

**Issue by bdkent** [spullara/mustache.java#128]
Hi,

I am trying to use mustache.java in an OSGi container. I am having an issue with this because the artifacts published to the standard maven repos do not seem to have proper OSGi attributes in the MANIFEST file.

You can see in all the raw artifacts:
https://repo1.maven.org/maven2/com/github/spullara/mustache/java/compiler/0.8.16/compiler-0.8.16.jar
https://repo1.maven.org/maven2/com/github/spullara/mustache/java/compiler/0.8.17/compiler-0.8.17.jar
https://repo1.maven.org/maven2/com/github/spullara/mustache/java/compiler/0.9.0/compiler-0.9.0.jar

None of them have `Bundle-SymbolicName`,  `Import-Package`, `Export-Package`, etc.

I saw other github issues related to OSGi that seem to suggest OSGi usage was supported.

Thanks!

**Comment by vincent-zurczak** [comment]
+1
Maven bundles are also valid JARs. So, making the compiler JAR a bundle should not impact current users. And it would greatly simplify the usage of Mustache in OSGi environments without wrapping it.

**Comment by vincent-zurczak** [comment]
I forked it and (re)added OSGi metadata in the compiler for version 0.9.x. That could be a PR.
Version 0.8.x lets me doubtful. Guava is available as an OSGi bundle. The real question is about JRuby. It is marked as provided. Why do we need it? Or more exactly, why is there a JRuby handler?

**Comment by spullara** [comment]
Let's go ahead and do this for 0.9. The JRuby provided dependency was to allow mustache to understand JRuby method / field lookup mechanisms and types.
