### ISSUE TITLE
Mustache can't parse template files?

### ISSUE THREAD

**Issue by tchoulihan** [spullara/mustache.java#129]
I'm trying to run mustache on a template file in the following way, but the method doesn't exist.

`mf.compile(new File(....));`

This seems like a no-brainer.

**Comment by bdkent** [comment]
I think you can just wrap it in a `java.io.FileWriter` like `mf.compile(new FileWriter(new File(....)));`

**Comment by spullara** [comment]
FileReader... but yeah.
