### ISSUE TITLE
Pattern used in encode method doesn't cover all cases

### ISSUE THREAD

**Issue by sandeeptv** [spullara/mustache.java#130]
The Pattern used to not encode the ascii characters in DefaultMustacheFactory.java doesn't cover the ascii code for "\n" which is "&#10; . The Pattern doesn't cover any of the special characters between "&" and ";" in the string.

`private static Pattern escapedPattern = Pattern.compile("^&\\w+;");`

**Comment by spullara** [comment]
We don't use this anymore.
