### ISSUE TITLE
Examples Maven issue

### ISSUE THREAD

**Issue by chaitan26** [spullara/mustache.java#133]
Hi ,
       Iam  trying to  build  examples project in the source on its own  . I  want to use  java 7 , hence modified the  compiler version to  0.8.17.  But still unable to build the project.

POM Iam  Using:

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.github.spullara.mustache.java</groupId>
  <artifactId>example</artifactId>
  <version>0.8.16-SNAPSHOT</version>
  <packaging>bundle</packaging>

  <dependencies>
   <dependency>
    <groupId>com.github.spullara.mustache.java</groupId>
    <artifactId>compiler</artifactId>
    <version>0.8.17</version>
</dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>2.3.2</version>
        <configuration>
          <source>1.7</source>
          <target>1.7</target>
          <encoding>UTF-8</encoding>
        </configuration>
      </plugin>
      <plugin>
         <groupId>com.github.spullara.mustache.java</groupId>
         <artifactId>mustache-maven-plugin</artifactId>
         <version>0.8.17</version>
        <executions>
          <execution>
            <configuration>
            </configuration>
            <goals>
              <goal>validate</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.felix</groupId>
        <artifactId>maven-bundle-plugin</artifactId>
        <version>2.3.7</version>
        <extensions>true</extensions>
        <configuration>
          <instructions>
            <Export-Package>_</Export-Package>
            <Import-Package>_</Import-Package>
          </instructions>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>

Error Iam getting:

Failed to execute goal com.github.spullara.mustache.java:mustache-maven-plugin:0.8.17:validate (default) on project example: Template deferredpartial.mustache not found

Can you please help me  to resolve the  issue, Iam new to mustache  and  experimenting out.

Thanks
Chaitan

**Comment by spullara** [comment]
Very hard to see the POM you are using in the issue. Can you put it in a gist and link it?
