### ISSUE TITLE
Custom function provides stringify value as input

### ISSUE THREAD

**Issue by golgoth14** [spullara/mustache.java#142]
I registered a function that convert date to localized string :
```java
    static class ToDateFunc implements Function<Object, String> {
        @Override
        public String apply(Object input) {
            if (input instanceof Date) {
                return DateHelper.format((Date) input);
            } else {
                throw new IllegalArgumentException("Date expected.");
            }
        }
    }
```

But input arg is a String that is the date.toString() !
How could I get the orignial value ?

Thank you.
Steve

**Comment by spullara** [comment]
There is no way to get the object. This type of thing should really be done in the view class rather than through the template. If you must do it this way, I would parse the date and reformat it.
