### ISSUE TITLE
Missing scala-extension-2.11 for Java 7

### ISSUE THREAD

**Issue by csaltos** [spullara/mustache.java#146]
So far there is:

scala-extensions-2.10 for Java 7 with version 0.8.17
scala-extensions-2.11 for Java 8 with version 0.9.0

But the scala-extensions-2.11 for Java 7 is missing. I think it could be published as version 0.8.17 for leaving 0.9.0 a Java 8 version only.

By the way, all of these is for using mustache at https://github.com/twitter/scrooge Thank you very much.

**Comment by eirslett** [comment]
+1 would love scala-extensions-2.11 for Java 7 with 0.8.17!

**Comment by spullara** [comment]
This is fixed in 0.8.18 and 0.9.1.
