### ISSUE TITLE
compilePartial() uses default tag delimiters {{ }}

### ISSUE THREAD

**Issue by panchenko** [spullara/mustache.java#148]
I would suggest adding the second TemplateContext parameter and using delimiters from it.

**Comment by panchenko** [comment]
The only question is how much efforts should we put in for making this backwards compatible e.g. if this function is overridden for whatever purpose.

**Comment by spullara** [comment]
This is the per the specification so it is unlikely to be changed. I could imagine a way to change it globally by allowing the overriding of the MustacheParser. Let me refactor that so you can do that.

**Comment by panchenko** [comment]
I see there is **Delimiters set in a parent template should not affect a partial** item there, however I am not sure if it should be applied when an outer template is called via `compile(Reader reader, String file, String sm, String em)`.  In this case I don't want any other separators. 
A good way to solve this could be passing separators in the constructor and apply them always.

**Comment by spullara** [comment]
I'll find a way to make it possible.
