### ISSUE TITLE
Template incompabilities

### ISSUE THREAD

**Issue by caiiiycuk** [spullara/mustache.java#154]
Hi. I have menu templates written in mustache in form like this:
```mustache
{{ some }}
{{ #list }}
  {{ name }}
{{ /list }}
```

This templates perfectly renders with janl/mustache.js. But this templates does not render correctly with mustache.java.

```mustache
{{ some }} - works as expected
{{ #list }} - does not works as list (just print one element)
```

Is it a bug?

**Comment by spullara** [comment]
That form isn't in the specification and is not supported by this implementation. I'm not sure off the cuff how hard it would be to support it - might be easy.

**Comment by caiiiycuk** [comment]
It is not critical, so i close this issue.
