### ISSUE TITLE
In the future please use more descriptive artifact names

### ISSUE THREAD

**Issue by agentgt** [spullara/mustache.java#156]
A small request. Its too late now for the existing maven modules but for future modules: 

For the artifact names please prefix your project's name or groupId or anything more descriptive than just `compiler`. That is `<artifactId>mustachejava-compiler</artifactId>` instead of `<artifactId>compiler</artifactId>`.

Otherwise in deployed wars you end up with jar names like `core-1232.jar` and `compiler-3423.jar` and your just waiting for a conflict. Yeah you can do some Maven configuration to make it add the groupId to the jar but its not the default and most don't know about it.

Even if you do fix the maven war  (prefix with groupId) issue there are tools like the *Eclipse Maven Dependency Hierarchy* that show only the artifact name (I believe the intellij version has the same issue as well but can't recall).

It has been pretty much the standard to prefix artifacts with your project name and there have been a plethora of new projects recently that seem to not follow this tradition.

I realize its too late now but please consider it for the future.

**Comment by spullara** [comment]
Thanks for the feedback.
