### ISSUE TITLE
Formatting Dates

### ISSUE THREAD

**Issue by BKaun** [spullara/mustache.java#158]
Is there a way to format Calendar/Date objects?

Something like {{#SomeDateFunc}} {{dateVar}} {{/SomeDateFunc}}

or perhaps {{dateVar | dateformat="MM/dd/yyyy"}}

I'm passing an object with a TemplateFunction function into the scope:

TemplateFunction TGUDateFormat() {
        return new TemplateFunction() {
          @Override
          public String apply(String input) {
            return input;
          }
        };
      }

But the "input" argument contains the variable name like scopeObject.someDateVar, but not the actual date substituted.

**Comment by jwils** [comment]
http://www.javarants.com/2013/03/09/mustache-is-logic-less-but-the-logic-has-to-go-somewhere/
