### ISSUE TITLE
ThreadLocal not removed, possible memory leak in servers with thread pools.

### ISSUE THREAD

**Issue by Revarye** [spullara/mustache.java#165]
Hi,

I'm using mustache.java in Tomcat, and have been seeing these messages related to `DefaultMustacheFactory.partialCache` in the logs upon app redeployment:

> SEVERE [ContainerBackgroundProcessor[StandardEngine[Catalina]]] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [webapp] created a ThreadLocal with key of type [com.github.mustachejava.DefaultMustacheFactory$1] (value [com.github.mustachejava.DefaultMustacheFactory$1@2c41da28]) and a value of type [java.util.HashMap] (value [{}]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

Would it be possible for mustache to `ThreadLocal.remove()` to clean up after the work is done?

Thank you.

**Comment by spullara** [comment]
Will investigate. The cache size is very limited and doesn't grow over time so I don't expect it to be an issue.

**Comment by spullara** [comment]
This has been fixed in master. https://github.com/spullara/mustache.java/commit/f1591fd815d25a57487090c6bb5f67d06e195305
