### ISSUE TITLE
Chaining template inheritance doesn't seem to work

### ISSUE THREAD

**Issue by AledLewis** [spullara/mustache.java#166]
I'm not sure if this is a bug or unsupported currently. 

I have a mustache layout file that I'm pretty reluctant to change (it's generated from the [gov uk template](https://github.com/alphagov/govuk_template)). I wanted to create a small extension of this base template to customise the application layout. I wanted to my application pages to further inherit from this. 

### layout_template.mustache
```html
{{{content}}}
```
### wrapper.mustache
```html
{{< layout_template}}
{{$content}}
<main id="content" role="main">
  {{{yield}}}
</main>
{{/content}}
{{/layout_template}}
```
### page.mustache
```html
{{< wrapper}}
{{$yield}}
This is the page content
{{/yield}}
{{/wrapper}}
```
I've worked around this by just compiling my page and passing that as a string to the content page.

**Comment by AledLewis** [comment]
Version 0.9.0

**Comment by spullara** [comment]
You can chain templates, but this isn't using template inheritance. If your layout template had {{$content}}{{/content}} and wrapper had {{$yield}}{{/yield}} it works.

https://github.com/spullara/mustache.java/blob/master/compiler/src/test/java/com/github/mustachejava/InterpreterTest.java#L232

**Comment by AledLewis** [comment]
Thanks, that worked perfectly. 

Is there a good documentation/reference page for the flavour of mustache that you've implemented?

**Comment by spullara** [comment]
Right now it is really just the README which points to the mustache specification and the template issue on that specification. That mostly covers what you can do with mustache.java without extending it. I do very much lack a description of how to extend mustache.java to implement features aside from the test code which has a very large number of examples but little documentation.
