### ISSUE TITLE
Clarify that List<Object> scopes must be modifiable, or avoid that requirement?

### ISSUE THREAD

**Issue by michaelhixson** [spullara/mustache.java#167]
I was caught off guard by the fact that `Mustache.execute(Writer, List)` modifies the input list.  It seems pretty natural to use `ImmutableList.of(...)` or `Arrays.asList(...)` for that argument, but doing so would result in an error.

I was about to make a pull request to add a paragraph to the javadoc`:

```
   * <p>The {@code scopes} list must be modifiable.  This method may invoke its
   * {@link List#add(Object)} and {@link List#remove(int)} methods.
```

...but I realized that `Mustache.run(Writer, List)` should probably also have that note.  Maybe there are more.

Can the modifiability requirement be avoided with refactoring somehow, without adding too much complexity or sacrificing performance?  The thrower in my case was [IterableCode.next(Writer, Object, List)](https://github.com/spullara/mustache.java/blob/dc87817c642ea98d3ceefafbf82ad6c1fc50f749/compiler/src/main/java/com/github/mustachejava/codes/IterableCode.java#L130).  There might be [others](https://github.com/spullara/mustache.java/blob/6124b6ffbb887af1c8c449681763aa248bc8ce67/compiler/src/main/java/com/github/mustachejava/DeferringMustacheFactory.java#L93) that make that same assumption, I'm not sure.

**Comment by spullara** [comment]
We need them to be modifiable for performance reasons but I don't like it either. I've put in a change that will replace the passed in List with an internal array list so there are no side effects and you don't need to worry about what kind of List you pass into the method.
