### ISSUE TITLE
Partials with different file extension

### ISSUE THREAD

**Issue by sbliven** [spullara/mustache.java#168]
I like to name my templates using the content's file extension so that syntax highlighting works. This seems to break partials, which assume that all templates have the same suffix.

So for example, I might have "bar.mustache.js" included by  "foo.mustache.html":

``` html
foo.mustache.html:
<html><head>
     <script type="text/javascript">
{{> bar.mustache.js }}
     </script>
...
```

It seems to me like partials should accept full filenames in addition to the current behaviour of matching the extension to the calling template.

**Comment by spullara** [comment]
I think that this might be an easy change that doesn't break backwards compatibility.

**Comment by zheng-wang** [comment]
+1

**Comment by spullara** [comment]
I thought this would be straightforward and backwards compatible but it isn't. Trying to figure out a way that would work.

**Comment by pathiery** [comment]
@spullara Hello and welcome to ... 6 years later ! Did [your commit ](https://github.com/si0005hp/mustache.java/commit/71868129829b07afc1cbad3bec8d92796c79c91e) fix this issue ?
I was looking for a way to support this feature in a project that uses a differently Mustache library/engine

**Comment by spullara** [comment]
I think it did but never heard back so probably didn't close it at the time.
