### ISSUE TITLE
Support for Implicit Iterator

### ISSUE THREAD

**Issue by Ferada** [spullara/mustache.java#171]
Rendering a list of strings into e.g. a HTML list is a bit of a hassle as the Implicit Iterator syntax isn't supported yet, c.f. https://github.com/mustache/spec/blob/master/specs/sections.yml#L141-L169 (unless I missed an equivalent way of doing that), so it would be great to add that feature.

**Comment by spullara** [comment]
All the spec tests are passing and that includes implicit iterators. We also have some equivalent tests in the unit tests: https://github.com/spullara/mustache.java/blob/master/compiler/src/test/java/com/github/mustachejava/InterpreterTest.java#L925

Maybe it is something to do with the particular thing you are attempting to iterate over? Do you have an example that isn't working?

**Comment by Ferada** [comment]
Ah right, so this might just be this specific case: What I have is a `List<String> attr` which is accessed in the template as `{{#attr}} ... {{.}} ... {{/attr}}` and it prints the surrounding object instead of the string in the loop (the correct number of times though).

What I ended up doing is creating a wrapper class `StringWrapper` that ... wraps the string so the interpolation worked fine with that.

**Comment by spullara** [comment]
How does your test differ from this test?

```java
  public void testImplicitIteratorWithScope() throws IOException {
    Mustache test = new DefaultMustacheFactory().compile(new StringReader("{{#test}}{{.}}{{/test}}"), "test");
    StringWriter sw = new StringWriter();
    test.execute(sw, new Object() {
      List<String> test = Arrays.asList("a", "b", "c");
    }).close();
    assertEquals("abc", sw.toString());
  }
```

**Comment by Ferada** [comment]
Found it, but it's actually something else, consider:

```java
    @Test
    public void testImplicitIteratorWithScope() throws IOException {
        Mustache test = new DefaultMustacheFactory().compile(new StringReader("{{#test}}{{.}}{{/test}}"), "test");
        StringWriter sw = new StringWriter();
        test.execute(sw, new Object() {
            List<String> test = Arrays.asList("a", null, "c");
        }).close();
        assertEquals("ac", sw.toString());
    }
```

That fails and tripped me up since I had `null` values in the list and really didn't expect that to suddenly print the enclosing object instead.

**Comment by spullara** [comment]
That would be expected since it will continue up the stack to find another scope if it finds a null in the current scope for a variable.

**Comment by Ferada** [comment]
Alright then.
