### ISSUE TITLE
TemplateFunction compile uses DEFAULT delimiters

### ISSUE THREAD

**Issue by dhakehurst** [spullara/mustache.java#177]
ValueCode.handleFunction uses DEFAULT_SM and DEFAULT_EM,

if these have been changed by the top level call, surely it should continue to use the changed values for em/sm

e.g.

DefaultMustacheFactory mf....
mf.compile(reader, template, "${", "}")

**Comment by spullara** [comment]
Yeah, this should definitely use the current ones.

**Comment by spullara** [comment]
Hmmm. Have to check why this isn't working as it does appear to be attempting to use the current template context. Will write a test for it and debug.

**Comment by spullara** [comment]
So my test passes. What version are you using?

```java
  @Test
  public void testWithTemplateFunction() throws IOException {
    DefaultMustacheFactory mf = new DefaultMustacheFactory();
    Mustache maven = mf.compile(new StringReader("Hello, ${#f}${foo}${/f}."), "maven", "${", "}");
    StringWriter sw = new StringWriter();
    maven.execute(sw, new Object() {
      TemplateFunction f = (s) -> {
        return s;
      };
      String foo = "Jason";
    }).close();
    assertEquals("Hello, Jason.", sw.toString());
  }
```

**Comment by spullara** [comment]
I found the place where it has this behavior. Doesn't seem to be for any good reason. Will change it.

**Comment by dhakehurst** [comment]
:-)
thanks

**Comment by jamesaspence** [comment]
Hi @spullara I'm still seeing this issue in 0.9.6, was this ever resolved? I found the exact culprit - `ValueCode#handleFunction`, L117 (https://github.com/spullara/mustache.java/blob/33badf405f5986b14fa5f141cdd883f9bd76f7ed/compiler/src/main/java/com/github/mustachejava/codes/ValueCode.java#L120)

**Comment by jamesaspence** [comment]
I should clarify, what I'm doing is calling it via `@{myTemplateFunction}` and that is using default delimiters. I noticed we have a test for using a template function via `${#f}${foo}${/f}` but this other syntax for calling `TemplateFunction` seems to have been left behind. I'd be happy to create a PR for it.

**Comment by jamesaspence** [comment]
To clarify I'm doing `@{fooBar}` where `fooBar` is a `TemplateFunction` that returns another string like `@{stuffThings}`. I've had to convert the enclosed placeholders to use default delimiters instead of my own, specified, custom delimiters.

**Comment by spullara** [comment]
I looked into it and the current behavior is the specified behavior. Function returns values should be parsed with default delimiters. There is probably a way to get around it by overriding the current behavior but I can't pass the spec with a different default behavior.

https://github.com/mustache/spec/blob/master/specs/%7Elambdas.yml#L44

**Comment by jamesaspence** [comment]
Hmmm, that seems... inconsistent. I'll escalate it up the chain and try to understand why they want that behavior. Thanks!
