### ISSUE TITLE
Can not change escaping of output

### ISSUE THREAD

**Issue by mrtoby** [spullara/mustache.java#178]
I am using mustache to generate json files, I realize that this not is the normal case, but it is my case. Say I use double curly to insert the string "that's all \"folks\"" into my template, the I get "that&#39;s all &#34;folks&#34;" in the output. That makes sense for HTML but not for json. I could try to use tripple curly to get around this problem, then I get "that's all "folks"" which not is a valid json string literal.

So I would like to be able to use my own favorite encoding use for double curly in my templates.

I tried to make a subclass of DefaultMustacheFactory with a different implementation of encode(..) but the factory instance in ValueCode (or actually in DefaultCode) is another instance of DefaultMustacheFactory than the one I used.

**Comment by spullara** [comment]
Hmm. There is only your instance of DefaultMustacheFactory. Do you have a test case that you can share that fails?

**Comment by spullara** [comment]
I'm going to close this as I don't think it is true, however, if you have a test case I am more than happy to reopen the issue and fix it.
