### ISSUE TITLE
Set Delimiter and triple braces

### ISSUE THREAD

**Issue by rui-p-oliveira** [spullara/mustache.java#179]
Hi,

If i use:

``` mustache
* {{default_tags}}
{{=<% %>=}}
* <% erb_style_tags %>
<%={{ }}=%>
* {{ default_tags_again }}
```

How can use variables with html like `{{{ someVariableWithHtml }}}` ?

Tks, this is a very good library :+1:

**Comment by spullara** [comment]
You should be able to use <%{ }%> to avoid escaping. At least that is what I am understanding you are asking about.

**Comment by rui-p-oliveira** [comment]
Yes! Thank you.
