### ISSUE TITLE
qq: how to throw on bad substitutions?

### ISSUE THREAD

**Issue by andy-d** [spullara/mustache.java#181]
I would like something like this test to work if possible, can you please help? Thanks!

``` java
public class BadSubstitutionTest {

    @Rule
    public ExpectedException expectedException = ExpectedException.none();

    static class Foo() {
        private String privateBar = "private bar";
    };

    @Test
    public void illegal_substitution_throws() throws Exception {
        String input = "A termite walks into a {{foo.privateBar}} and says is the bartender here?";
        Writer writer = new StringWriter();
        MustacheFactory mustacheFactory = new DefaultMustacheFactory();

        StringReader reader = new StringReader(content);
        Mustache mustache = mustacheFactory.compile(reader, content);

        expectedException.expect(IllegalArgumentException.class);
        mustache.execute(writer, ImmutableMap.of("foo", new Foo()));
    }
```

**Comment by andy-d** [comment]
Found the old issue with the workaround for this though it is awkward. Any plans to build something in?

Thanks again!

**Comment by spullara** [comment]
Ah, it currently ignores private fields rather than failing with them. If you create a subclass of ReflectionObjectHandler and use that for your ObjectHandler you can override the checkMethod/checkField methods to throw a different exception that isn't ignored. It will propagated up as the cause of a MustacheException but otherwise similar to your example.

```
    mf.setObjectHandler(new ReflectionObjectHandler() {
      @Override
      protected void checkField(Field member) throws NoSuchFieldException {
        if ((member.getModifiers() & Modifier.PRIVATE) == Modifier.PRIVATE) {
          throw new IllegalArgumentException("Only public, protected and package members allowed");
        }
      }
    });
```

**Comment by spullara** [comment]
As to your question about building it in, no. There are so many possible configurations that it is truly just easier to make it possible to override for any particular kind of change that people would like. Instead I went the route to make almost all behavior changeable by the developer.
