### ISSUE TITLE
scala-extensions for 2.12.X?

### ISSUE THREAD

**Issue by daviddenton** [spullara/mustache.java#182]
Is there a plan to add support for the new Scala version? I don't mind submitting a PR to get it done (assuming it's not blocked), but would like to know that it would get released.

:)

**Comment by spullara** [comment]
Please submit a PR for it and I will pull it in.

**Comment by schmitch** [comment]
@spullara I actually created a PR that is know merged https://github.com/spullara/mustache.java/pull/192, would it be possible to create a release for that?

**Comment by spullara** [comment]
I should be able to cut a release today.

**Comment by spullara** [comment]
0.9.5 has been released. May take some time to propagate to the mirrors.
