### ISSUE TITLE
Data for Partials

### ISSUE THREAD

**Issue by d0x7** [spullara/mustache.java#191]
Hello,

I'm trying to use mustache together with Jersey, but I'm experiencing a strange issue when using Partials.
Jersey offers a module for Mustache Java so it works just fine, I can use partials as expected.
To handle exceptions with jersey, you can specify an ExceptionMapper, but these ExceptionMappers don't support Mustache, so I decided to create my "own" instance of a MustacheFactory just for the ExceptionMappers. And here's my issue: When using my own MustacheFactory, partials aren't rendered as expected. For example:

```JAVA
MustacheFactory mustacheFactory = new DefaultMustacheFactory();
Mustache mustache = mustacheFactory.compile("templates/someTemplate.mustache");
StringWriter stringWriter = new StringWriter();
mustache.execute(stringWriter, ImmutableMap.of("title", "Some title!"));
System.out.println(stringWriter.toString());
```

header.mustache
```HTML
<!DOCTYPE html>
<html>
<head>
    <title>{{ title }}</title>
</head>
<body>
```

someTemplate.mustache
```HTML
{{>templates/header}}
<h1>This is mustacheee</h1>
```
(And a footer, but that's not important for now.)

The expected output would be

```HTML
<!DOCTYPE html>
<html>
<head>
    <title>Some title!</title>
</head>
<body>
<h1>This is mustacheee</h1>
```

But instead, the <title> Tag is empty.

As mentioned before, when using Mustache with Jersey, it works like a charm.

Does someone know, what the issue is? Is there any way to specify data for partials (in Java)?

**EDIT:** Okay, it seems to be working when I'm using a different MustacheFactory every time I render a template. Is that the expected behavior?

**Comment by d0x7** [comment]
What the hell. 

I was about to close the issue because it worked for a second (I didn't change anything).
Now, I tried the same again and it's not working anymore (Same Issue as above)

**Comment by spullara** [comment]
That shouldn't be necessary. If it is possible to make it happen in a simple test case I would be happy to look at it. Certainly the title tag should only be empty if you aren't passing in the data when you execute.

**Comment by spullara** [comment]
Checked in a test for this. Except for needing to change the partial include to {{>header}} it works fine for me. Here is the change: https://github.com/spullara/mustache.java/commit/0c7e10216b0ad0d8b3950fbeb504d6aa810bcbc2

Please reopen the issue with your own failing test if you haven't gotten past the problem you ran into.
