### ISSUE TITLE
how to render #{{{some_var}}}

### ISSUE THREAD

**Issue by wyzssw** [spullara/mustache.java#193]
I want render 
```
AND {{tfield}} = #{{{name}}.{{{jfield}}}}
```
to
```
AND someOtherId= #{someId}
```
To avoid the conflict of mustache(which `{` is the starter symbol in mustache)
i must modify to
```
AND {{tfield}} = #{ {{name}}.{{{jfield}}}} 
```
which has a space between `#{` and `{{name` , is ANY good way to bypass this conflict?

**Comment by spullara** [comment]
Probably the easiest way is to temporarily change the delimiters. I've checked in a test that shows you how you would do that:

https://github.com/spullara/mustache.java/blob/master/compiler/src/test/java/com/github/mustachejava/DelimiterTest.java#L82
