### ISSUE TITLE
Consider adding "Automatic-Module-Name" to MANIFEST.MF for greater JPMS compatibility

### ISSUE THREAD

**Issue by fwgreen** [spullara/mustache.java#194]
Mustache, at least the last time I tried it, works with Java 9 modules.  When imported as an automatic module it comes up as its artifact name `compiler`.  This probably isn't sufficient for a module name.  This [blog post](http://blog.joda.org/2017/05/java-se-9-jpms-automatic-modules.html) has some practical solutions.

**Comment by spullara** [comment]
Is this sufficient?

https://github.com/spullara/mustache.java/commit/f405e966ab4e82e0fd52bf518e1a0a23275dcc5c

results in:

```
Manifest-Version: 1.0
Archiver-Version: Plexus Archiver
Created-By: Apache Maven
Built-By: sam
Build-Jdk: 9
Automatic-Module-Name: com.github.mustachejava
```

**Comment by fwgreen** [comment]
Maybe `com.github.spullara.mustachejava`?  Just to make sure there is no risk of there ever being a name collision.

**Comment by spullara** [comment]
I was following the rules that were laid out which ask you to name them after the top level package of the classes. I was tempted to name it like I do for maven though. Not sure which way is best. Honestly I don't think there will be overlap.
