### ISSUE TITLE
empty collection

### ISSUE THREAD

**Issue by emicklei** [spullara/mustache.java#195]
The mustache.js seems to have a feature to skip content based on the emptiness of a collection.

```
            {{#links.length}}
            <div class="single category">

                   {{#links}}
                    <li>
                        <p>{{{description}}}</p>
                    </li>
                    {{/links}}

            </div>
            {{/links.length}}
```

It looks like this feature is not supported/implemented in this Java version?

**Comment by spullara** [comment]
0 isnt false in Java so we don’t support it. You can use {{^links.isEmpty}} though.

**Comment by emicklei** [comment]
thx
