### ISSUE TITLE
Translate String directly

### ISSUE THREAD

**Issue by yuting-liu** [spullara/mustache.java#196]
Hi,

I saw through `DefualtMustacheFactory` API, there are many different `compile` methods implemented. However, I didn't find one that could directly translate string using mustache template to the result string and not involve in file writes.

There are many methods relevant to read in the file and then translate the result and write into the file. I'm wondering whether we could have one that implements the translation of strings with templates.

**Comment by spullara** [comment]
It is somewhat awkward because it hasn't been a super common use case but you can use:

```java
mustacheFactory.compile(new StringReader("Template goes here: {{test}}"), "nameUsedForErrorReporting");
```

If you are using templates embedded in code a lot I would probably make a small helper method that does that.

**Comment by Siva10** [comment]
@spullara I'm looking to compile with templates embedded in code. Is there helper method added in any of the versions ?

**Comment by spullara** [comment]
There isn't.

**Comment by xiaoyihu** [comment]
I also want to compile with templates embedded in code.

**Comment by rajaneeshm** [comment]
mustacheFactory.compile(new StringReader("Template goes here: {{test}}"), "nameUsedForErrorReporting");  This method can take only one param,
I wanted to supply a map of multiple objects , is that possible?

**Comment by spullara** [comment]
Compilation and execution are separate. After you compile it, you can then execute() it and provide a map of multiple objects to be used on template evaluation.

**Comment by rajaneeshm** [comment]
Thank  you very much @spullara ,

I found this is easy with Handlebars.
