### ISSUE TITLE
A minor variable name change request.

### ISSUE THREAD

**Issue by melvinma** [spullara/mustache.java#197]
In the DefaultMustacheFactory class, if we could change "resourceRoot" to "classpathResourceRoot", it will be fantastic. I did not get it before and thought it was file path, it took me 2 hours to figure out that I should pass File object to the constructor. Thanks.

`  /**
   * Use the classpath to resolve mustache templates.
   *
   * @param resourceRoot the location in the resources where templates are stored
   */
  public DefaultMustacheFactory(String resourceRoot) {
    this.mustacheResolver = new DefaultResolver(resourceRoot);
  }`

**Comment by spullara** [comment]
Makes sense. I will update it with your suggestion.

**Comment by spullara** [comment]
https://github.com/spullara/mustache.java/commit/b71540f93a5a7bf9d688ab3035d717764c3a1e33
