### ISSUE TITLE
\n character isn't present in rendered template 

### ISSUE THREAD

**Issue by nikoncode** [spullara/mustache.java#199]
Hi. 

```
    public static void main(String[] args) throws IOException {
        List<Map<String, String>> hits = Arrays.asList(
                Collections.singletonMap("value", "1"),
                Collections.singletonMap("value", "2"),
                Collections.singletonMap("value", "3"));

        Map<String, Object> params = Collections.singletonMap("hits", hits);

        MustacheFactory mf = new DefaultMustacheFactory();
        Mustache mustache = mf.compile(new StringReader("{{#hits}}{{value}}\n{{/hits}}END\n"), "asd");
        mustache.execute(new PrintWriter(System.out), params).flush();
    }
```

Code presented above should render` 1\n2\n3\nEND\n` but it render `123END\n` instead.

**Comment by spullara** [comment]
That is purposeful so that you don't have a bunch of useless whitespace but still format your templates nicely.

**Comment by nikoncode** [comment]
It's sound pretty logical for me and original library support that.

It's good idea to force formatting, but what if mustache template is part of smth more (e.g. json request)?

**Comment by spullara** [comment]
Generally you can manipulate the template text to get the formatting you are looking for. In your case, I think you can change the template to be:

```
{{#hits}}
{{value}}
{{/hits}}
END
```

That should give you the rendering you are looking for in this case but generally you can get the right rendered format. Also, re: JSON, don't use templates, use a JSON writing library like Jackson :)
