### ISSUE TITLE
javadoc is down (s3)

### ISSUE THREAD

**Issue by CSchnackenberg** [spullara/mustache.java#200]
[http://mustachejava.s3-website-us-west-1.amazonaws.com/apidocs/index.html](http://mustachejava.s3-website-us-west-1.amazonaws.com/apidocs/index.html)

seems to be offline.

**Comment by spullara** [comment]
I need to regenerate them and host them somewhere with a better domain name. You should be able to generate them by doing "mvn javadoc:javadoc -pl :compiler", then find them in compiler/target/site/apidocs/index.html.

**Comment by jmsalcido** [comment]
@spullara why dont host it here in github?
https://vaadin.com/blog/host-your-javadoc-s-online-in-github

**Comment by spullara** [comment]
Moved the hosting to GitHub:

http://spullara.github.io/mustache/apidocs/
