### ISSUE TITLE
Provide a means to define a super-template variable in sub-template, with inheritance

### ISSUE THREAD

**Issue by azurvii** [spullara/mustache.java#201]
e.g.
base.html:
```
{{#jsUrl}}<script src="{{jsUrl}}"></script>{{/jsUrl}}
```
chat.html:
```
{{<base.html}}
{{! Somehow define jsUrl here, rather than in Java. }}
{{/base.html}}
```

If it is implemented / has an equivalent workaround and I'm just simply ignorant, please help to point me at the reference/code how I should do it.
Soy template's [`call`](https://developers.google.com/closure/templates/docs/commands#call) allows defining variables in the sub-template, which are declared in the super-template.
It's possible to pass `jsUrl` in from Java, but I think this is a constant that should be part of the template rather than a variable defined in code.
Turning `{{jsUrl}}` into `{{$jsUrl}}{{/jsUrl}}` block is also a workaround, but it's requiring sub-template writing more duplicated template code. (So it'd become:
base.html:
```
{{$jsUrl}}{{/jsUrl}}
```
chat.html:
```
{{<base.html}}
{{$jsUrl}}<script src="/js/chat.js"></script>{{/jsUrl}}
{{/base.html}}
```
and with more sub-templates coming up, the <script> boilerplate would violate DRY.)

**Comment by spullara** [comment]
We looked at doing this in the spec and decided not to do it. However, you can abuse the ability to extend mustache.java pretty badly and add new behaviors with pragmas. I checked in some code that adds a new pragma 'set' where you can do things like:

```
{{%set jsUrl=test}}
```

You then need to override extension so those pragmas get copied into the base templates so they get executed. Be careful with this implementation, last set will win.

https://github.com/spullara/mustache.java/commit/2346a6d676561a7863591b481d675dbaf74afb60

**Comment by spullara** [comment]
There was a proposal from another implementer on the original template inheritance issue I filed against the specification that isn't terrible. The essential idea is that it introduces another operator that can check to see if a section has an override or not. Taking a look at implementing it as it could be useful for cases like this one.

**Comment by spullara** [comment]
This feature is now in master. I have confidence that it will be permanently added. Here is what your example looks like:

base.html:
```
{{?jsUrl}}<script src="{{$jsUrl}}{{/jsUrl}}"></script>{{/jsUrl}}
```

chat.html:
```
{{<base.html}}
{{$jsUrl}}URL{{/jsUrl}}
{{/base.html}}
```

result:
```
<script src="URL"></script>
```

This maintains an equivalent amount of logic to the normal template operations and lets you do more powerful things with template inheritance. Thanks for pushing me to revisit this — I think that this will make templates even more powerful without introducing any breaking changes or contortions.
