### ISSUE TITLE
Passing null scope to DefaultMustache::execute breaks it forever

### ISSUE THREAD

**Issue by davidmortiz** [spullara/mustache.java#204]
Passing a null scope to DefaultMustache.execute effectively breaks the it forever.  The issue seems to be related to this piece of code in GuardedBinding which always picks the first wrapper it finds.

https://github.com/spullara/mustache.java/blob/master/compiler/src/main/java/com/github/mustachejava/reflect/GuardedBinding.java#L63-L82

I've written up a quick test case that demonstrates the issue
```java
    @Test
    public void testCase() {
        String template = "Hello {{user.name}}";

        DefaultMustacheFactory factory = new DefaultMustacheFactory();
        Mustache m = factory.compile(new StringReader(template), "test");

        Map<String, Object> scopes = ImmutableMap.of("user", ImmutableMap.of("name", "Test"));

        //Expected this to output 'Hello'
        String result =  m.execute(new StringWriter(), (Map<String, Object>) null).toString();
        System.out.println(result); //prints 'Hello'

        //Expected this to output 'Hello Test' instead prints 'Hello'
        result = m.execute(new StringWriter(), scopes).toString();
        System.out.println(result); //prints 'Hello'
    }
```

I'm not sure how much of a problem this really is, I suspect passing a null scope object isn't really a valid use case.  However, the fact that this causes the compiled Mustache to fail to render forever is a bit scary.

**Comment by spullara** [comment]
Interesting. Thanks for filing it. Doesn't seem like it should break it.

**Comment by spullara** [comment]
This test works and I have added it to the tests.
