### ISSUE TITLE
Add the ability to find templates on the module path

### ISSUE THREAD

**Issue by fwgreen** [spullara/mustache.java#207]
Mustache can't find its resources when running on the Java module system.

**Comment by spullara** [comment]
What is the easiest way to reproduce this?

**Comment by fwgreen** [comment]
I think a similar approach to the one used here might be a solution to the problem:
https://github.com/ebean-orm/ebean/issues/1367

**Comment by fwgreen** [comment]
My apologies.  I'm just realizing that my problem stems from how various tools assemble modularized projects.  Using Eclipse or Idea, the template directory can't be read from within resource directory, but is visible from the project root.  But if I build my jar with the Maven Assembly Plugin, the contents of the resource directory are placed in the project root automatically.
