### ISSUE TITLE
Add the ability to check size array

### ISSUE THREAD

**Issue by KrifaYounes** [spullara/mustache.java#208]
I need to know the array size in mustache it's possible ? 

example : 
{{#array.size == 1}} 
<div> todo </div>
{{\array.size}}

{{#array.size == 2}} 
<div> todo2 </div>
{{\array.size}}

**Comment by spullara** [comment]
This is the wrong place to put that code. You should put it in a view class that has all the logic you need. I've written a blog on my thoughts on this and how you should implement Mustache in practice:

https://javarants.com/mustache-is-logic-less-but-the-logic-has-to-go-somewhere-3e976b7a49c8
