### ISSUE TITLE
Dump a map as JSON

### ISSUE THREAD

**Issue by imduffy15** [spullara/mustache.java#209]
If I pass the following:

```
Map<String, Object> scope = new HashMap<String, Object>();
Map<String, String> exampleValue = new HashMap<String, String>();
exampleValue.put("key", "value")
scope.put("example", exampleValue);
```

To a template of:

```
{{{example}}}
```

I get back

```
{ key=value }
```

as the output. Is there any way to get this as a valid json string?

**Comment by spullara** [comment]
You would need to use a JSON generator. Put a view class between your data and the template and use code like the following to generate the JSON you need:

https://stackoverflow.com/questions/17819710/is-there-any-way-to-convert-a-map-to-a-json-representation-using-jackson-without

If you are using Java 9 or above you can also use the built in JSON support without adding another dependency.

http://www.oracle.com/technetwork/articles/java/json-1973242.html
