### ISSUE TITLE
new lines seems to be randomly rendered or consumed

### ISSUE THREAD

**Issue by JohnMTu** [spullara/mustache.java#213]
@Parameters(value = {
            "b{{#list}}B{{.}}A{{/list}}a | bB1AB2Aa",
            "b\n{{#list}}B{{.}}A{{/list}}a | b\nB1AB2Aa", // new line before start of iteration is rendered
            "b{{#list}}\nB{{.}}A{{/list}}a | bB1AB2Aa", // new line right after start of iteration is NOT rendered
            "b{{#list}}\n{{.}}{{/list}}a | b12a", // new line right after start of iteration is NOT rendered
            "{{#list}}\n{{.}}{{/list}}a | 12a", // new line right after start of iteration is NOT rendered
            "b{{#list}}\n\nB{{.}}A{{/list}}a | b\nB1A\nB2Aa", // double new line right after start of iteration is rendered once (workaround to above case)
            "b{{#list}}{{.}}\n{{/list}}a | b12a", // new line as end of iterated section is NOT rendered, if content is only that variable !!!!!!!!!!!!!!!!
            "b{{#list}}{{.}}{{.}}\n{{/list}}a | b1122a", // new line as end of iterated section is NOT rendered, if content has only variables but no static text !!!!!!!!!!!!!!!!
            "b{{#list}}{{.}}xx{{.}}\n{{/list}}a | b1xx1\n2xx2\na", // new line as end of iterated section is rendered, if content has static text between variables
            "b{{#list}}B{{.}}A\n{{/list}}a | bB1A\nB2A\na", // new line as end of iterated section is rendered, if line has some other content that variable

            // like cases before, but with \n after {{/list}} which is Also NOT always rendered
            "b{{#list}}B{{.}}A{{/list}}\na | bB1AB2A\na",
            "b\n{{#list}}B{{.}}A{{/list}}\na | b\nB1AB2A\na",
            "b{{#list}}\nB{{.}}A{{/list}}\na | bB1AB2A\na",
            "b{{#list}}\n{{.}}{{/list}}\na | b12\na",
            "{{#list}}\n{{.}}{{/list}}\na | 12a", // not rendered !!!!!!!!!!
            "b{{#list}}\n\nB{{.}}A{{/list}}\na | b\nB1A\nB2A\na",
            "b{{#list}}{{.}}\n{{/list}}\na | b12\na",
            "b{{#list}}{{.}}{{.}}\n{{/list}}\na | b1122\na",
            "b{{#list}}{{.}}xx{{.}}\n{{/list}}\na | b1xx1\n2xx2\n\na",
            "b{{#list}}B{{.}}A\n{{/list}}\na | bB1A\nB2A\n\na",
    })
    @Test
    public void ignoringNewLines(String template, String expectedOutput) {
        assertThat(MustacheFactoryWrapper.generateText(template, new MustacheTestDto().withList("1", "2"))).isEqualTo(expectedOutput);
    }

**Comment by spullara** [comment]
They are consumed when there is only whitespace and a mustache block tag start or end on a line. Otherwise you end up with a bunch of unnecessary new lines in the output.

**Comment by JohnMTu** [comment]
would like to know logic when is newline consumed and when preserved. Atm i'm really lost. It's not so relevant for HTML rendering, but for rendering stuff, which is displayed 1:1 it's crucial to get new lines in predictable way.

**Comment by JohnMTu** [comment]
well, this has also static text on line, but it's consumed:
b{{#list}}\nB{{.}}A{{/list}}a 
renders as bB1AB2Aa

**Comment by spullara** [comment]
That one is surprising to me but probably because I would never write template text in that style. The rule in the code is one above plus if it just started an iterable also elide it. The idea was to make the HTML output look a bit better than from most other libraries that end up with newlines everywhere if you write readable template text. It doesn't make it great if you are rendering things that are very whitespace dependent without being careful about where you put your tags. For example, you can write things like:

```
<ul>
{{#list}}
  <li>{{item}}</li>
{{/list}}
</li>
```

and not get extra new lines between the tags instead of having to write something like:

```
<ul>
{{#list}}  <li>{{item}}</li>
{{/list}}
</li>
```

to get something that outputs nice html. When I have used it to generate non-html I never ran into a case that wasn't representable but there could certainly be edge cases.
