### ISSUE TITLE
java 11 support

### ISSUE THREAD

**Issue by rmannibucau** [spullara/mustache.java#217]
Hi,

Java 11 has a String.value() method and it leads Element (of decorated collection) to be quite unusable

Here is the workaround i'm using - in a custom ReflectionObjectHandler:

                @Override // java 11 support
                protected AccessibleObject findMember(final Class sClass, final String name) {
                    if (sClass == String.class && "value".equals(name)) {
                        return null;
                    }
                    return super.findMember(sClass, name);
                }

it would be great to integrate it somehow.

**Comment by spullara** [comment]
I wonder if a better change would be to by default to ignore non-public members and not throw an exception. Thanks for the PR and I'm going to think about it for a bit.

**Comment by rmannibucau** [comment]
It would but it is a breaking change

**Comment by spullara** [comment]
Probably should have been like that from the beginning but makes debugging a pain in the ass. Integrating your change for now. There are some things I would like to break at some point...
