### ISSUE TITLE
Cannot use template from outside the project folder

### ISSUE THREAD

**Issue by laurent-thiebaud-gisaia** [spullara/mustache.java#219]
Hi. 

I need to read the templates from outside the project folder. So I tried:

```
MustacheFactory mf = new DefaultMustacheFactory(myExternalPath);
Mustache mustache = mf.compile("myfilename");
```

But this fails with a MustacheNotFoundException. First I passed the absolute path to the compile method, but this also crashes because "File not under the root".

In my understand, the DefaultResolver:

```
public DefaultResolver(String resourceRoot) {
    this.classpathResolver = new ClasspathResolver(resourceRoot);
    this.fileSystemResolver = new FileSystemResolver();
  }
```
should be changed to 
`this.fileSystemResolver = new FileSystemResolver(resourceRoot);`

But maybe this is an unwanted use case?

Thanks.

**Comment by spullara** [comment]
Instead of using that constructor, pass in a File root to the DefaultMustacheFactory rather than a String.

**Comment by laurent-thiebaud-gisaia** [comment]
It's working thanks!
