### ISSUE TITLE
Template inheritance does not work with relative paths to files in parent directory inside JAR

### ISSUE THREAD

**Issue by bucht** [spullara/mustache.java#220]
Loading 'layout.mustache' from a JAR fails when using relative paths like:
```
{{<../layout}}
 ```
Normalisation of the file path in DefaultMustacheFactory#resolvePartialPath would resolve it.

```
public String resolvePartialPath(String dir, String name, String extension) {
    String filePath = name;

    // Do not prepend directory if it is already defined
    if (!name.startsWith("/")) {
      filePath = dir + filePath;
    }

    // Do not append extension if it is already defined
    if (!name.endsWith(extension)) {
      filePath = filePath + extension;
    }

    String path = new File(filePath).getPath();
    return ensureForwardSlash(path);
  }
```
Perhaps the most unintrusive change would be changing the second to last line to:
```String path = new File(Paths.get(filePath).normalize().toString()).getPath();```

**Comment by bucht** [comment]
One work around would be to use absolute paths, but since relative paths works when loading from a directory structure instead of a JAR-file it's very confusing.

**Comment by spullara** [comment]
When you are pulling from the class path it doesn't use the that code to resolve the location. Can you post a failing test case?

**Comment by bucht** [comment]
Perhaps dropwizard is setting something up the wrong way then. I'm running from within a fat jar, but I'll check if I can create a minimal app.

**Comment by spullara** [comment]
Looks like it potentially uses the file constructor or resolves templates relative to the class. You might need to override this behavior.

https://github.com/dropwizard/dropwizard/blob/master/dropwizard-views-mustache/src/main/java/io/dropwizard/views/mustache/MustacheViewRenderer.java#L78
