### ISSUE TITLE
Seems to repeat the substring from the end of the tag to the end of the containing string

### ISSUE THREAD

**Issue by spiderpete** [spullara/mustache.java#221]
Example case:
Input: "{{name}} - {{email}} 1" -> Actual Output: "{{name}} - {{email}} 1 1"; Expected Output "{{name}} - {{email}} 1"

https://github.com/spullara/mustache.java/blob/f7a0c86f1c640d66f2456f94267f3de3d4ba1f57/compiler/src/test/java/com/github/mustachejava/InterpreterTest.java#L1509

**Comment by spullara** [comment]
Interesting. Must be a bug in the identity code. Investigating.

**Comment by spullara** [comment]
Looks like that test should have:

```java
                  if (object == null) {
                    identity(writer);
                    return writer;
                  } else {
                    return super.execute(writer, scopes);
                  }
```

**Comment by spullara** [comment]
https://github.com/spullara/mustache.java/commit/e274b65f343ed6c0200adfd852576ab8752319f4
