### ISSUE TITLE
Add a java.nio.file.Path-based resolver, for non-default file systems

### ISSUE THREAD

**Issue by michaelhixson** [spullara/mustache.java#223]
Add a `MustacheResolver` implementation that accepts a `java.nio.file.Path` root in its constructor, and which does not internally convert that `Path`  to a `java.io.File`.

**Q:** "Why don't you just use `new FileSystemResolver(path.toFile())`?"

**A:** Calling `path.toFile()` will throw `UnsupportedOperationException` if the path is not using the default file system.  I'm running into this as I try to use an in-memory file system ([Jimfs](https://github.com/google/jimfs)) instead of the default real file system during tests.

~~To sidestep any compatibility issues, I suggest putting this in a new top-level class in the `com.github.mustachejava.resolver` package rather than changing any existing resolvers.~~
**Edit:** Actually, I suggest adding a `FileSystemResolver(Path)` constructor but avoiding changes to the `File`-using code paths.

**Let me know if I should work on a PR with this change.**  The base JDK lets you create a `Path` with a non-default file system using zip files, so it should be possible to test the new resolver properly without pulling in any new dependencies like Jimfs.

```java
Path zipFile = Path.of("archive.zip");

try (FileSystem zipFileSystem = FilesSystems.newFileSystem(zipFile, null)) {
  Path mustacheRoot = zipFileSystem.getPath("templates");

  Path templateFile = mustacheRoot.resolve("hello.mustache");
  List<String> lines = Files.readAllLines(templateFile); // This works, for example.

  try {
    MustacheResolver brokenResolver = new FileSystemResolver(mustacheRoot.toFile()); // throws
    throw new AssertionError("should have thrown");
  } catch (UnsupportedOperationException expected) {}

  MustacheResolver newResolver = new NioFileSystemResolver(mustacheRoot); // One possible name...

  // TODO: Test the new resolver
}
```

**Comment by spullara** [comment]
File a PR. Seems reasonable to me.

**Comment by michaelhixson** [comment]
@spullara Do you have time to look at the PR?  https://github.com/spullara/mustache.java/pull/224
