### ISSUE TITLE
can I set default value for templete field

### ISSUE THREAD

**Issue by lordk911** [spullara/mustache.java#226]
I want to use mustache.java to support when user write a sql statment he/she can define some parameter , so the sql user write was a templete , how can I let the user define default value?

**Comment by spullara** [comment]
I think I know what you are asking but could you give an example? I'm tempted have your users just provide a set of defaults as a map separately. For example, if the SQL statement was:

```sql
SELECT * FROM table WHERE key = '{{key}}'
```

You could also collect from them a default mapping:

```
key = foo
```

I don't think there is a nice way to do that as part of the template that would be simple enough for your use case. You could make a custom value key parser that figured it out by splitting the reference by = or something like that so the statement would look like:

```sql
SELECT * FROM table WHERE key = '{{key=foo}}'
```

But that is a lot more work.

**Comment by lordk911** [comment]
@spullara  thanks for your reply .

I've tried to change code GuardedBinding.createAndGet method . even though it's not good ,but it works for me:

````
private Object createAndGet(List<Object> scopes) {
    // Make a new wrapper for this set of scopes and add it to the set
    String[] kv = name.split("\\|");
    String key = name;
    String value = null;
    if(kv.length==2){
      key = kv[0];
      value = kv[1];
    }
    Wrapper wrapper = getWrapper(key, scopes);
    previousSet.add(wrapper);
    if (prevWrappers == null || prevWrappers.length != previousSet.size()) {
      prevWrappers = previousSet.toArray(new Wrapper[previousSet.size()]);
    }
    // If this fails the guard, there is a bug
    try {
      if (wrapper instanceof MissingWrapper && !key.equals(name)){
        return value;
      }
      return oh.coerce(wrapper.call(scopes));
    } catch (GuardException e) {
      throw new GuardException("BUG: Unexpected guard failure: " + key + " " + previousSet + " " + singletonList(scopes));
    }
  }
````
my test template : 
````
"Hello {{name|mustache.java}} \n" + "You have just won ${{value}}! \n" + "{{#in_ca}} "
				+ "Well, ${{taxed_value}}, after taxes. \n" + "{{/in_ca}} "
````

output:

````
Hello mustache.java 
You have just won $10000! 
 Well, $6000.0, after taxes. 
````

**Comment by spullara** [comment]
Here is an alternative that doesn't require you to change the library. Tested fairly lightly:

```java
    DefaultMustacheFactory mf = new DefaultMustacheFactory(root);
    mf.setObjectHandler(new ReflectionObjectHandler() {
      @Override
      public Wrapper find(String name, List<Object> scopes) {
        int i;
        if ((i = name.indexOf("|")) != -1) {
          String newName = name.substring(0, i);
          String defaultValue = name.substring(i + 1);
          Wrapper wrapper = super.find(newName, scopes);
          if (wrapper instanceof MissingWrapper) {
            return scopes1 -> {
              // Test the guards returned in the missing wrapper
              wrapper.call(scopes1);
              return defaultValue;
            };
          }
          return wrapper;
        }
        return super.find(name, scopes);
      }
    });
    Mustache m = mf.compile(new StringReader("{{test}} {{test2|bar}} {{test3|baz}}"), "testDefaultValue");
    StringWriter sw = new StringWriter();
    m.execute(sw, new Object() {
      String test = "foo";
      String test2 = "BAR";
    });
    assertEquals("foo BAR baz", sw.toString());
```

**Comment by mfarkan** [comment]
Hello, I've a template like this;

`<html><head></head><body><p>Merhaba {{userName}} - {{orderDate}} - {{orderNumber}} {{#isVisible}} hesabınız oluşturuldu.{{/isVisible}} {{{component.header}}}</p></body></html>`

However, when I try to execute mustache with parameters without isVisible boolean flag, it deletes it from the template but I need to keep it from here because I've another rendering process in another app. How can I solve this?
