### ISSUE TITLE
IntelliJ IDEA doesn't recognize template syntax correctly

### ISSUE THREAD

**Issue by bxqgit** [spullara/mustache.java#229]
Is this library using some kind of custom syntax or it's a bug in IntelliJ IDEA plugin?

**Comment by spullara** [comment]
Do you have an example? It may be that the Intellij plugin doesn't support the latest mustache spec proposed changes like inheritance.

**Comment by Ustimov** [comment]
In my case this related to the inheritance syntax.

**Comment by spullara** [comment]
https://youtrack.jetbrains.com/issue/WEB-10883

**Comment by bxqgit** [comment]
Thank you for reporting this bug to JetBrains!

**Comment by spullara** [comment]
Well that was quick: https://youtrack.jetbrains.com/issue/WEB-10883 is now fixed/closed.
