### ISSUE TITLE
Disable encoding for certain variables

### ISSUE THREAD

**Issue by kenston** [spullara/mustache.java#230]
#147 demonstrates how Mustache can be customized to enable/disable encoding/escaping of values (e.g., to HTML entities), and it works for me.

However, there are cases where I'd like to enable escaping (global/by default), then for selected variables, I'd like to disable encoding regardless if the template uses `{{` or `{{{`.

For example,
```
Hello {{nonEncodable}}, this is {{encodable}}
```
where `nonEncodable` is `<b>1</b>` and `encodable` is `<b>2</b>`, should render as:
```
Hello <b>1</b>, this is &lt;b&gt;2&lt;/b&gt;
```

I can almost do it by overriding `com.github.mustachejava.DefaultMustacheFactory#encode`:
```java
  @Override
  public void encode(String value, Writer writer) {
    escape(value, writer);
  }
```

but if only we have the parameter `Object object` which is the source of that `value` (the one in `oh.stringify(object)`), so I can check whether that `object` possess the marker of whether escaping should be done or not.

Let me know if there is a better way to achieve the same.

**Comment by spullara** [comment]
I would probably wrap the value in an escape / no escape object.

**Comment by kenston** [comment]
Cool. So it's something we can wait for in a future release then?

**Comment by spullara** [comment]
Probably not. It is a pretty specific use case that anyone who really needs it could implement themselves. I try to make sure that everything is extensible in such a way that any interesting feature can be implemented without change the mustache source and this fits in that category.

**Comment by kenston** [comment]
I see, so may I know how it can be extended for that use case?

> I would probably wrap the value in an escape / no escape object.

My variable value object already contains the flag on whether to escape or not, but this object doesn't reach the `com.github.mustachejava.DefaultMustacheFactory#encode`.

**Comment by spullara** [comment]
Ah I see. Let me take a look. Maybe we can fix that. Worst case you could
check that at a higher level.

Sam

**Comment by spullara** [comment]
Ok, it is possible but kind of ugly. Working on a test now to show you how it can be done.

**Comment by spullara** [comment]
https://github.com/spullara/mustache.java/commit/33badf405f5986b14fa5f141cdd883f9bd76f7ed

**Comment by spullara** [comment]
Going to close this unless it doesn't work for you use case and then we can talk more about it.

**Comment by kenston** [comment]
@spullara, thanks for taking a look into this one. I initially thought of something like the one you shared in 33badf4, but it seems to risk missing some cases especially if the code evolves later on.

Currently, it misses cases where the object is not to be encoded (e.g., `NotEncoded`) but it comes out from a `Function` (going through `com.github.mustachejava.codes.ValueCode#handleFunction`) or a `Callable` (going through `com.github.mustachejava.codes.ValueCode#handleCallable`. That is, I feel it might be safer to override/attack it from `com.github.mustachejava.codes.ValueCode#execute(java.io.Writer, java.lang.String)` or ultimately `com.github.mustachejava.DefaultMustacheFactory#encode`.

May I know your thoughts on this one?

**Comment by spullara** [comment]
It is too late there as it has already been stringified. If you also want to handle those cases, the changes to my example should be pretty easy.

**Comment by kenston** [comment]
> It is too late there as it has already been stringified. 

I think it's not too late yet, since the stringified object isn't encoded and rit emains the same raw String value that will be used, so `com.github.mustachejava.DefaultMustacheFactory#encode` just needs a way to be able to get the origin/source `object` so it can check whether to encode or not:
```java
@Override
  public void encode(String value, Object object, Writer writer) {
    // Put if condition to check if object instanceof NotEncode
    escape(value, writer);
  }
```
then I can override only that method. This lessens risk as the codebase changes as well. I wonder if we can take this route?

> If you also want to handle those cases, the changes to my example should be pretty easy.

But if I override `com.github.mustachejava.codes.ValueCode#execute(java.io.Writer, java.util.List<java.lang.Object>)`, I might have to duplicate then modify from `handleFunction` and `handleCallable`.

**Comment by kenston** [comment]
Hi @spullara, any feedback on the above comment?

**Comment by kenston** [comment]
@spullara, can we re-open ticket, please?
