### ISSUE TITLE
Appending random string starting with 'm_-' to classes after rendering the template

### ISSUE THREAD

**Issue by D0NNY** [spullara/mustache.java#239]
When adding styles classes to a template, after rendering the template in html the class name of each class get appended by a random string starting with 'm_-' which will not render the css
![Screenshot from 2019-08-30 19-10-26-croped](https://user-images.githubusercontent.com/29435936/64025348-1b7a3600-cb5a-11e9-8479-f1da4bab34dc.png)

**Comment by spullara** [comment]
My guess is that your code is doing this rather than the mustache.java code. Do you have any more information about the issue?

**Comment by D0NNY** [comment]
> My guess is that your code is doing this rather than the mustache.java code. Do you have any more information about the issue?

Sorry for the late replay, I have been working on some other projects and got no time to spend on this. This code is passed as a message body to emails, and I only looked at the code from the mail page, I'm have a guess maybe this is updated in by the mail provider, but I'm not sure and I'll come back after I check that. Also I'm using nodeJs for this, if that will help in any debugging. Thanks for the replay

**Comment by D0NNY** [comment]
Oh sorry for reporting opening an issue on the wrong build Ill close this and open another for nodeJs build
