### ISSUE TITLE
Exceptions happening in lambdas are not reported conveniently

### ISSUE THREAD

**Issue by newcron** [spullara/mustache.java#243]
Hi there, 

first of all: thanks for this great library! I've been using it heavily over the last couple of years, and really love it! 

This is the first time, I found a small inconvenience with it: 

assume a template like this: 

```
hello {{#timesTwo}}4{{/timesTwo}}
```

and a lambda like this (dummy code, might contain errors): 

```
class TimesTwoLambda extends Function<String, String> {
    @Override
    public String apply(String s) throws IOException {
        return Integer.valueOf(s) * 2; 
    }
} 
```

with this template: 

```
hello {{#timesTwo}}a{{/timesTwo}}
```

the above function would throw a number format exception (expected) however, mustache will just pass this exception on. 

I am right now having a case with a large template (containing a complex legal document), where such a function is used several times. If one of them produces an exception (an error I am having right now), it's extremely difficult to find out, which case it was, as there is no information about where in the template this error happened. 

It would be really great to catch a `RuntimeException` and wrap it in a `MustacheException` in the catch block surrounding this line: 

https://github.com/spullara/mustache.java/blob/6625bd88a188d59fdd9a2b15ce8bcfbec6273233/compiler/src/main/java/com/github/mustachejava/codes/IterableCode.java#L112

that would cause the `RuntimeException` to be wrapped so that it would be easier to identify the position in the template where the error happened. 

thanks a lot, 
Matthias

**Comment by spullara** [comment]
Thanks for the high praise. Looking at the issue.

**Comment by spullara** [comment]
Fixed. Will try and release sometime soon. a925db0

**Comment by spullara** [comment]
0.9.7 released
