### ISSUE TITLE
library version inconsistency notice.

### ISSUE THREAD

**Issue by kaifeng-h** [spullara/mustache.java#247]
Hi. I have implemented a tool to detect library version inconsistencies. Your project have 2 inconsistent libraries and 1 false consistent library.

Take org.scala-lang:scala-library for example, this library is declared as version 2.11.4 in scala-extensions/scala-extensions-2.11, 2.12.2 in scala-extensions/scala-extensions-2.12, 2.10.4 in scala-extensions/scala-extensions-2.10 and etc... Such version inconsistencies may cause unnecessary maintenance effort in the long run. For example, if two modules become inter-dependent, library version conflict may happen. It has already become a common issue and hinders development progress. Thus a version harmonization is necessary.

Provided we applied a version harmonization, I calculated the cost it may have to harmonize to all upper versions including an up-to-date one. The cost refers to POM config changes and API invocation changes. Take org.scala-lang:scala-library for example, if we harmonize all the library versions into 2.13.0. The concern is, how much should the project code adapt to the newer library version. We list an effort table to quantify the harmonization cost. 

The effort table shows the overall harmonization cost on APIs. It seems your project have no API invokes on this library, which could be safely upgrade to 2.13.0

|Index|Module|NA(NAC)|NDA(NDAC)|NMA(NMAC)|
|-|-|-|-|-|
|1|scala-extensions/scala-extensions-2.11|0(0)|0(0)|0(0)|
|2|scala-extensions/scala-extensions-2.12|0(0)|0(0)|0(0)|
|3|scala-extensions/scala-extensions-2.10|0(0)|0(0)|0(0)|
|4|..|..|..|..|

Also we provided another table to show the potential files that may be affected due to library API change, which could help to spot the concerned API usage and rerun the test cases. 

As for false consistency, take com.github.spullara.mustache.java compiler jar for example. The library is declared in version [0.9,) in all modules. However they are declared differently.  As components are developed in parallel, if one single library version is updated, which could become inconsistent as mentioned above, may cause above-mentioned inconsistency issues

If you are interested, you can have a more complete and detailed report in the attached PDF file.
[spullara mustache.java.pdf](https://github.com/spullara/mustache.java/files/4273013/spullara.mustache.java.pdf)

**Comment by spullara** [comment]
The scala stuff has been supported by the community, aka not me, from the beginning. I would worry about changing it now as folks are using it. Maybe change it for new releases of scala?
