### ISSUE TITLE
Could we trim extra whitespace in the template?

### ISSUE THREAD

**Issue by Huanghuiying0624** [spullara/mustache.java#254]
Given the following template:  
<img width="380" alt="Screen Shot 2020-11-09 at 2 50 04 PM" src="https://user-images.githubusercontent.com/33543101/98504643-e2c80780-229a-11eb-9839-b8009e184d5f.png">
  
It will be rendered as the following html:
<img width="388" alt="Screen Shot 2020-11-09 at 2 44 17 PM" src="https://user-images.githubusercontent.com/33543101/98504403-3f76f280-229a-11eb-9140-637ae5bfad3f.png">

Expected rendered html:
<img width="257" alt="Screen Shot 2020-11-09 at 4 09 59 PM" src="https://user-images.githubusercontent.com/33543101/98510263-2116f400-22a6-11eb-92e1-7b3dbc4ac1dd.png">

Do we have any solution to trim the leading/trailing whitespace in the template?

**Comment by spullara** [comment]
You can add trimming by overriding the encode method, be careful you don't trim necessary spaces though.

https://github.com/spullara/mustache.java/blob/3e59ba4c685fbc515c9b85166a9349e3d45ef1c3/compiler/src/main/java/com/github/mustachejava/DefaultMustacheFactory.java#L126
