### ISSUE TITLE
Illegal reflective access by mustachejava.reflect.BaseObjectHandler

### ISSUE THREAD

**Issue by liamsdunn** [spullara/mustache.java#256]
Hello, my software is throwing the following error when building:

```
WARNING: Illegal reflective access by com.github.mustachejava.reflect.BaseObjectHandler to to method java.util.HashMap$Node.getKey()
WARNING: Please consider reporting this to the maintainers of com.github.mustachejava.reflect.BaseObjectHandler
```
Are there any mitigation strategies/ plans to fix this?

**Comment by spullara** [comment]
Unlikely, I think. The changes to module access in JDK 9+ may make this kind of thing impossible. I'll see if there is any workaround but generally private reflective access is looked down upon.

**Comment by liamsdunn** [comment]
Ah I see, well thank you for any help you can provide! Technically, it is just a warning for the time being, but future releases will make it an actual error. Maybe something to consider for the future.

**Comment by spullara** [comment]
My guess is that you have {{key}} while enumerating a hash map. The issue is that the Node class isn't public inside HashMap and it is calling getKey() on it. I may have to change the findMember code if the class isn't public to use reflection without the warning. This would require to first interrogate the interfaces and supertypes and otherwise fail. I can see how this may be fixable. Can you verify that you are doing what I think you are doing?

**Comment by spullara** [comment]
I think this may fix it.

https://github.com/spullara/mustache.java/compare/59a85ef2a4db...99ee0192b4c2

**Comment by spullara** [comment]
That passes the build and I added a new test that ensures that it can still access Node.getKey() without spewing out the warning messages. I did realize looking at the code though that folks that are accessing private/protected classes in the core JDK will still see the warning and will likely fail at a later date.

**Comment by InvisibleTech** [comment]
We are using this library in our project, and as we port to Java 16 we hit this issue. We only need the Java mustache part itself and have built the SNAPSHOT that fixes this locally. However, is there a plan to move this SNAPSHOT into a public Maven repo as an release candidate or something?  Or even build the release version to a public repo?

**Comment by spullara** [comment]
I'll do a release soon that will have the change.

**Comment by rschmitt** [comment]
This change is exactly what I need, but I don't see version 0.9.8 in Maven Central.

**Comment by ddsharpe** [comment]
@spullara Please publish 0.9.8 to Maven.  See https://mvnrepository.com/artifact/com.github.spullara.mustache.java/compiler

**Comment by spullara** [comment]
Trying to recover the ability to publish. Apparently PGP stuff started failing.
