### ISSUE TITLE
Dynamic rendering

### ISSUE THREAD

**Issue by dragonnikkirocks** [spullara/mustache.java#257]
Hi,
i want to dynamically render a document using Mustache.java. I saw an issue where there is a discussion abt using dynamic partials.
https://github.com/janl/mustache.js/pull/242
Is there something like this in mustache.java? If so, Can someone help with an example?

TIA

**Comment by spullara** [comment]
You could extend it to do this. I'll take a stab at it and if successful add it to the tests.

**Comment by spullara** [comment]
Going to take some amount of cleverness as right now the compiler assumes that all templates are static. Still think it is possible to implement but might take some time.

**Comment by spullara** [comment]
This is not super well tested but you can try it for your use case with the current version of mustache.java as it doesn't require any changes to the core.

**Comment by spullara** [comment]
I'm closing this due to no response but I think I answered it.
