### ISSUE TITLE
ScalaObjectHandler throws run-time error under Scala 2.13.5

### ISSUE THREAD

**Issue by bwbecker** [spullara/mustache.java#258]
Line 70 uses the Traversable class which is no longer present in the 2.13.x libraries.  It throws a ClassNotFound error when instantiated.

I made a local copy of that class, changed the Traversable to Iterable and it seems to be working fine.

**Comment by spullara** [comment]
Can you make a pull request and I will integrate it for the next release?

**Comment by spullara** [comment]
I believe that your change was integrated and released in mustache 0.9.10
