### ISSUE TITLE
Thank you, I was able execute to StringWriter however...

### ISSUE THREAD

**Issue by mcroteau** [spullara/mustache.java#262]
Greetings, I was able to execute to StringWriter however I am getting some undesired results. It looks as if the execute executes twice, leaving one iteration unchanged. Here is an example:

Beginning string:

"<span>{{zero}} {{one}}</span>"

Results:
"<span>{{zero}} {{one}}</span> <span>zerocontent onecontent</span>"

Thank you.

**Comment by spullara** [comment]
That doesn't make much sense to me. Can you show me the code that produces that?

**Comment by mcroteau** [comment]
Thank you, forgive me for taking so long to get back to you. Here is a sample project. https://github.com/aspen-projects/a2. I created a separate branch for it named `spullara`. 

The template logic is within **n/http/HttpDispatcher** class, line 103.

```
  Writer out = new StringWriter();
  out.append(raw);

  MustacheFactory mf = new DefaultMustacheFactory();
  Mustache mustache = mf.compile(new StringReader(out.toString()), "Template issue:");
  mustache.execute(out, exchangeData).flush();
```

There is no rush, thank you for your time.

**Comment by spullara** [comment]
This is because you are using the same StringWriter for output as you used for the input so it is just appending to it.

**Comment by mcroteau** [comment]
This is what I ended up with and it worked great.

```
Writer in = new StringWriter();
in.append(raw);

Writer out = new StringWriter();

MustacheFactory mf = new DefaultMustacheFactory();
Mustache mustache = mf.compile(new StringReader(in.toString()), "Template issue:");
mustache.execute(out, exchangeData).flush();

System.out.println(out.toString);
```

Thanks

**Comment by spullara** [comment]
Awesome!
