### ISSUE TITLE
Security: Insecure default behavior: local files and classes can be leaked

### ISSUE THREAD

**Issue by schirrmacher** [spullara/mustache.java#263]
I threw a fuzzer on your serializer and discovered that it is possible to load local files and classes by serializing the following templates:

`"{{>secret-file.txt"` or `"{{>SecretManager.class"`

This behavior **should be documented very clearly** and be turned off by default. I have seen vulnerable implementations using your library where malicious user input could leak private server files and classes of an application.

I really had to dig deep to understand why this is possible ([DefaultResolver](https://github.com/spullara/mustache.java/blob/f0f4f17aef57bc2f9106d906b333a634877c8b4f/compiler/src/main/java/com/github/mustachejava/resolver/DefaultResolver.java#L48)):
```kotlin
  public Reader getReader(String resourceName) {
      Reader reader = classpathResolver.getReader(resourceName);
      if(reader == null) {
        reader = fileSystemResolver.getReader(resourceName);
        if (reader == null) {
          reader = uriResolver.getReader(resourceName);
        }
      }
      return reader;
  }
```

**Comment by spullara** [comment]
Updated the README to state explicitly that this isn't designed to use untrusted templates from 3rd parties. https://github.com/spullara/mustache.java/commit/28d8a4a88a8c4a402259d1ff5088b6bd8e99719f

**Comment by spullara** [comment]
Added a SafeMustacheFactory that will allow folks to use the library with untrusted templates. I can't change the default as that would be extremely unexpected backwards compatible change.

**Comment by schirrmacher** [comment]
Thank you very much!
