### ISSUE TITLE
Provide a safe MustacheFactory designed to allow untrusted templates

### ISSUE THREAD

**Issue by spullara** [spullara/mustache.java#264]
Some developers using mustache.java would like the ability to safely allow untrusted parties to provide templates. The DefaultMustacheFactory is not designed for this as it has no protection for reading files both from the filesystem, classpath or even the internet. Providing a SafeMustacheFactory will allow these developers to build this feature without doing the work themselves to ensure that untrusted templates can't access sensitive information.

**Comment by fvztdk** [comment]
Hi, great feature.

Can we get a example of the input of the constructor of SafeMustacheFactory ? 

I'm not sure what allowedResourceNames should be.

**Comment by spullara** [comment]
There are some tests:

https://github.com/spullara/mustache.java/blob/main/compiler/src/test/java/com/github/mustachejava/InterpreterTest.java#L59

Basically the list of allowed resources has to match the provided mustache or partial names that you intend to compile exactly.

**Comment by spullara** [comment]
I'm going to close this as it is released.
