### ISSUE TITLE
Add character number in `Improperly closed variable` exception message

### ISSUE THREAD

**Issue by manasjoshi14** [spullara/mustache.java#266]
I got this error in a really long single-line string in a project 
Had to find the issue using a debugger. Can we add the character number taken from the reader `br` in this error message as well? 

https://github.com/spullara/mustache.java/blob/c17bb110161848e444576e93170a2a696770e9d3/compiler/src/main/java/com/github/mustachejava/MustacheParser.java#L217

**Comment by spullara** [comment]
Added the name of the variable and the character location.
