### ISSUE TITLE
Resource directories are treated as files in ClasspathResolver class

### ISSUE THREAD

**Issue by sdilts** [spullara/mustache.java#268]
The `ClassPathResolver` class treats folders as valid resources for templating, which causes issues if you accidentally specify a folder name or empty string as a resource.

### Steps to reproduce

``` java
// there is a folder called "templates" in the resources dir (src/main/resources/templates)
MustacheFactory mustacheFactory = new DefaultMustacheFactory("templates");

// expect it to throw a MustacheNotFoundException here, but doesn't
Mustache template = mustache.compile("");

StringWriter writer = new StringWriter();
// throws a null pointer exception here
mustache.execute(writer, Map.of());
```

1. Create an empty folder in your resources directory
2. Create a `DefaultMustacheFactory` with the class path resource root set to that folder
3. Use the factory to create a Mustache object. 

__Expected Result__: A `MustacheNotFoundException` or some other error should be thrown, as there is not a file there.
__Actual Result__: Nothing happens.

You can cause the same thing to occur if you don't specify a resource root and just use a folder name as the resource name:
``` java
MustacheFactory mustacheFactory = new DefaultMustacheFactory();
Mustache template = mustache.compile("templates");
```

### Cause

This occurs because the `ClasspathResolver` class treats folders as valid targets: a list of filename separated by newlines gets put into the reader returned by `ClaspathResolver::getReader` instead of an error being generated. The method should probably check to see if it is reading a file or directory before continuing.

**Comment by spullara** [comment]
Seems reasonable.

**Comment by spullara** [comment]
So the problem I am running into is that getResourceAsStream is succeeding. Investigating if there is something I can do about it.

**Comment by spullara** [comment]
Ok, I think I have this resolved for both the jar case and the file case. https://github.com/spullara/mustache.java/commit/efb67c494c79bc0a5da169fe78d2c19a884cd435
