### ISSUE TITLE
base64-encoded value is url-encoded?

### ISSUE THREAD

**Issue by pumoica** [spullara/mustache.java#269]
A template includes a place holder that must be populated with a base64-encoded value. However, the value seems to get url-encoded before it is placed in the template. Here is an example to reproduce this issue:

try
        {
            String encodedStr = Base64.getEncoder().encodeToString("john.doe".getBytes(StandardCharsets.UTF_8.toString()));
            System.out.println("Encoded String: " + encodedStr);
            Map<String, Object> placeHolderValueMap = new HashMap<>();
            placeHolderValueMap.put("username", encodedStr);
            Writer writer = new OutputStreamWriter(System.out);
            MustacheFactory mf = new DefaultMustacheFactory();
            Mustache mustache = mf.compile(new StringReader("Test: >>>{{username}}<<<"), "example");
            mustache.execute(writer, placeHolderValueMap);
            writer.flush();
            writer.close();
        }
        catch(Throwable t)
        {
            log.info("Failed to test.", t);
        }

Expected result: Test: >>>am9obi5kb2U=<<<
Actual result: Test: >>>am9obi5kb2U`&#61;`<<<

Note that the sign "=" is converted into "&#61"

**Comment by spullara** [comment]
If you want to avoid encoding use triple stash or override encode in the factory. The default implementation does HTML encoding.

**Comment by pumoica** [comment]
Hi, thank you for the answer. 

I must say that coming from using mustache primarily as a code generator it is (very) unusual to see it being used in the context of exposing its functionality to a user via an HTML interface so that it should by default do any modifications to the provided input. 
And I could not find any mentioning of HTML encoding as the default implementation in your documentation either.
Could you clarify how exactly this html encoding can be disabled? A code example would be very helpful...

**Comment by spullara** [comment]
By the spec, which we follow very closely except for perfect whitespace matching, mustache values are encoded by default. Not sure what version of mustache that you were using where that isn't the default.

https://mustache.github.io/mustache.5.html
