### ISSUE TITLE
boolean section are not merged

### ISSUE THREAD

**Issue by stlcn2000** [spullara/mustache.java#275]
The following code will generate an output "Hello",
public static void main(String[] argv) {
        MustacheFactory mustacheFactory = new DefaultMustacheFactory();
        Mustache mustache = mustacheFactory.compile(new StringReader("{{#a.b}}{{a.c}}{{/a.b}}"), "template");
        Map data = new HashMap();
        HashMap a = new HashMap();
        a.put("b", "b");
        a.put("c", "Hello");
        data.put("a", a);
        StringWriter stringWriter = new StringWriter();
        try {
            mustache.execute(stringWriter, data).flush();
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }

        System.out.println(stringWriter.getBuffer().toString());
    }
Output: Hello

While the following code generate nothing,
public static void main(String[] argv) {
        MustacheFactory mustacheFactory = new DefaultMustacheFactory();
        Mustache mustache = mustacheFactory.compile(new StringReader("{{#a.b}}{{c}}{{/a.b}}"), "template");
        Map data = new HashMap();
        HashMap a = new HashMap();
        a.put("b", "b");
        a.put("c", "Hello");
        data.put("a", a);
        StringWriter stringWriter = new StringWriter();
        try {
            mustache.execute(stringWriter, data).flush();
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }

        System.out.println(stringWriter.getBuffer().toString());
    }

We expect the c can be extracted from the context of a.

**Comment by spullara** [comment]
Well the cause is obvious to me, we don't implement {{#a.b}} as {{#a}}{{#b}} so there is no a context. Let me look at the spec and see what it says if it even mentions this case.

**Comment by spullara** [comment]
As per the specification, the current behavior is correct. No intermediate contexts will remain on the stack when evaluating dotted names. To get the behavior you want you will need to have separate sections.
