### ISSUE TITLE
{{json}}

### ISSUE THREAD

**Issue by coderzpw1** [spullara/mustache.java#276]
Use the "mustache" syntax, for example: {JSON}}. The initial value of the "JSON" variable is {name ":" Zhangsan "}, but the value obtained by using {JSON}} is {name = Zhangsan}. In this case, an error is reported in the post request. How can I solve it?

**Comment by spullara** [comment]
Sounds like the .toString() method on your JSON variable doesn't serialize it properly. A test would be helpful if you would like further help.
