### ISSUE TITLE
Indentation isn't honoured in functions that return multiple lines

### ISSUE THREAD

**Issue by kevinwright** [spullara/mustache.java#278]
The problem appears to be double-nesting of IndentWriter within a partial.  The outermost instance correctly sets `this.prependIndent = true` in the `write()` loop, but the nested instance only honours nesting of the first subsequent line before `flushIndent()` resets it to false.

What I think needs to happen is that whenever `prependIndent` is set, it also needs to be set in `inner` if that's an `IndentWriter` too, and so on for however many of them are nested

**Comment by spullara** [comment]
Hmm. Not at a computer but I think the assumption was that it would ultimately call the write method that was overridden. Will look into this tonight. Do you have a trivial test case you could post?

**Comment by kevinwright** [comment]
I've been digging a bit - my initial assumption was wrong. Description updated.

**Comment by kevinwright** [comment]
Tested and confirmed a fix.

The problem goes away by having a `setPrependIndent` method in `IndentWriter` that recursively calls itself in `inner` if that's *also* an `IndentWriter`

**Comment by kevinwright** [comment]
I'm feeling nice, so I made a pull request with tests included. Still some odd behaviour with disappearing newlines in there I need to fix as well though.

**Comment by spullara** [comment]
Thanks!
