### ISSUE TITLE
Deferred loading of partials

### ISSUE THREAD

**Issue by kenston** [spullara/mustache.java#280]
Given template:
```
{{#enable}}{{>rsrc.html}}{{/enable}}
```
with `enable` variable usually false (i.e., null), the `rsrc.html` is always loaded/read even if it will not be used. I think it makes sense, since during compilation it wouldn't know if it's going to be used or not, and since compilation is ideally a one-time thing.

Since I compile the template on-demand rather than re-use the `Mustache` object, is it possible to do compilation of the template that defers the reading of `rsrc.html` only when actually needed? Or to combine `compile` and template's `execute` into one so that it would know that it didn't have to load `rsrc.html`?

I assume `com.github.mustachejava.DeferringMustacheFactory` with docs:
> This allows you to automatically defer evaluation of partials. By default it generates HTML but you can override that behavior.

isn't appropriate for my case, right?

Example code:
```java
MustacheFactory mf = new DefaultMustacheFactory(new DefaultResolver() {
            public Reader getReader(String resourceName) {
                System.out.println("  Called getReader: " + resourceName);
                return new StringReader("contentBeingIncluded");
            }
        });

mf.compile(new StringReader("{{#enable}}{{>rsrc}}{{/enable}}"), "example1");
```

Actual Output:
```
  Called getReader: rsrc.html
```

**Comment by spullara** [comment]
Compilation will always read and compile rsrc.html in your example. You could make a method that compiles and runs the template at runtime and put it in triple staches.

**Comment by kenston** [comment]
> You could make a method that compiles and runs the template at runtime and put it in triple staches.

@spullara, can you share some examples of how to do this? Thanks!

**Comment by spullara** [comment]
Small example: https://github.com/spullara/mustache.java/commit/8c97ec40dc3ce5ce38dc8601bbfea8ffc45f1e87
