### ISSUE TITLE
Better option of handling missing template variables?

### ISSUE THREAD

**Issue by vaclavsvejcar** [spullara/mustache.java#287]
Hi,

I'm looking for some nice way how to handle missing variables in Mustache templates during the execution.

```java
final MustacheFactory factory = ...;
final Mustache template = factory.compile(new StringReader("Hello, {{name}}!", "test-template"));

// 'name' variable not provided here,
// renders the template without any issue, but I'd need it to fail at this point
template.execute(writer, Map.of());
```

The only feasible way I found, when I need to get both missing variable name and template name is this:

```java
    private static MustacheFactory checkMissingVariablesMustacheFactory() {
        final DefaultMustacheFactory mustacheFactory = new DefaultMustacheFactory();
        mustacheFactory.setObjectHandler(new ReflectionObjectHandler() {
            @Override
            public Binding createBinding(String name, TemplateContext tc, Code code) {
                return new GuardedBinding(this, name, tc, code) {
                    @Override
                    protected synchronized Wrapper getWrapper(String name, List<Object> scopes) {
                        final Wrapper wrapper = super.getWrapper(name, scopes);

                        if (wrapper instanceof MissingWrapper) {
                            throw new MissingTemplateVariableException(tc.file(), name);
                        }

                        return wrapper;
                    }
                };
            }
        });

        return mustacheFactory;
    }
```

It's working nice, but it's quite verbose. Is there any easier way to do that, or if not, did you consider adding some kind of handler for this case?

Thank you and thanks for this great library!

**Comment by agentgt** [comment]
If your model is mostly objects that are not Map then my library can statically check missing variables:

https://github.com/jstachio/jstachio

It is mostly compatible with mustache.java and you can still use mustache.java and just it JStachio for checking.

**Comment by spullara** [comment]
The intent is to not add a lot flags / configuration and for folks to override things in the API that they want to change as the number of variations that people want would be untenable. Since you only need to write that code once and use it like a library, it seems reasonable to me.
