### ISSUE TITLE
HTML tokens are being encoded as they are replaced

### ISSUE THREAD

**Issue by jchambers-crescendo** [spullara/mustache.java#288]
I've got my replacement tokens containing some html tags:
`<p>some text<b />etcetera</p>`, but when I they are run through the mustache compiler, they are not replacing the `<div>{{replaceMe}}</div>` token as is, they are getting encoded and I'm ending up with:
`<div>&lt;p&gt;some text.&lt;br /&gtetcetera&lt;/p&gt;</div>`

Is there a way to turn this encoding off?

**Comment by jchambers-crescendo** [comment]
For clarity and good measure, here is the test code I'm using to demonstrate the issue:
```java
MustacheFactory mustacheFactory = new DefaultMustacheFactory();

Map<String, String> tokens = new HashMap<>();
tokens.put("replace", "<p>some text<br />et cetera</p>");
String template = "<div>{{replace}}</div>";

Mustache mustache = mustacheFactory.compile(new StringReader(template), null);
StringWriter writer = new StringWriter();
mustache.execute(writer, tokens);

System.out.println(writer);
```

current output is:
`<div>&lt;p&gt;some text&lt;br /&gt;et cetera&lt;/p&gt;</div>`

expected output is:
`<div><p>some text<br />et cetera</p></div>`

**Comment by spullara** [comment]
All HTML is encoded by the default encoder. If you are trying to put HTML you will need to use triple mustache to avoid encoding. It isn't great though and you should figure out how to not do that and keep all HTML in a template since it puts you in danger of introducing HTML from data.

**Comment by spullara** [comment]
From the specification: https://github.com/mustache/spec/blob/master/specs/interpolation.yml#L44
