### ISSUE TITLE
Migrate jackson from 2.7.4 to 2.14.x

### ISSUE THREAD

**Issue by timothee-peron** [spullara/mustache.java#290]
Hello,

There are several security issues using jackson 2.7.4 databind, see vulnerabilities here:
[https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind](https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind)

Could the jackson version be updated to 2.14?

Thanks

**Comment by spullara** [comment]
I updated it though it didn't really matter as it was only used in test. 64e6e3f
