### ISSUE TITLE
Escape forward slash issue

### ISSUE THREAD

**Issue by PongPong** [spullara/mustache.java#294]
if the value contains forward slash , it does not escape.

```
template: <div>{{value}}</div>

actual: "foo/bar" -> "foo/bar"
expected: "foo/bar" -> "foo&#x2F;bar"
```

**Comment by spullara** [comment]
I do think that mustache.js does escape the forward / but it has been not escaped for so long I am a little hesitant to change it in mustache.java as it may break non-html use cases. Sadly only these are the only ones in the specification:

https://github.com/mustache/spec/blob/master/specs/interpolation.yml#L46

**Comment by PongPong** [comment]
maybe it is better to provide a option to enable custom/extra html escape in factory class?

**Comment by spullara** [comment]
You can override the "encode" method in DefaultMustacheFactory to change escaping behavior:

https://github.com/spullara/mustache.java/blob/3433d0cb0801c7d879b905704399bdc972c2788e/compiler/src/main/java/com/github/mustachejava/DefaultMustacheFactory.java#L126

By default it delegates to HtmlEscaper but you can have it do whatever you like.
