### ISSUE TITLE
MustacheNotFoundException since 0.9.12

### ISSUE THREAD

**Issue by panghy** [spullara/mustache.java#303]
Seeing `MustacheNotFoundException` after https://github.com/spullara/mustache.java/commit/a58f7a206f75690d817280376d519f016abbb4cb?diff=split&w=0

Likely uber jar issue

**Comment by ianlevesque** [comment]
@panghy is this fixed on 0.9.13? I think it might've been a recent regression I introduced (and quickly fixed)

**Comment by spullara** [comment]
fixed
