### ISSUE TITLE
Defect or User Error? No output for Dynamic Names

### ISSUE THREAD

**Issue by Hamilton-dfp** [spullara/mustache.java#305]
Hi, the specification seems to have at least one typo regarding [Dynamic Names](https://mustache.github.io/mustache.5.html#:~:text=name%7D%7D%3C/strong%3E%0A%7B%7B/names%7D%7D-,Dynamic%20Names,-Partials%20can%20be), so I don't know if the problem I am facing is confusion about the specification, a defect in mustache.java, or if I am just plain wrong.

## Code to Reproduce:

src/main/java:
```
public static void main(String[] args) {
        MustacheFactory mf = new DefaultMustacheFactory();
        Mustache m = mf.compile("pd-test.mustache");

        StringWriter writer = new StringWriter();

        m.execute(writer, Map.of("name", "dn"));

        System.out.println(writer);
    }
```

src/main/resources:

pd-test.mustache:
```
Do dynamic names work?

Answer: {{*name}}
```

dn.template:
```
Templates Do!
```

dn.mustache:
```
Mustache Do!
```

## Expected Output:
```
Do dynamic names work?

Answer: Mustache Do!
```
or
```
Do dynamic names work?

Answer: Templates Do!
```

Depending on whether the named template should end in `.template` or `.mustache` (Specification example says `.template`, but that seems weird so I tried `.mustache` just to be safe, see Additional Notes below).

## Actual Results:
```
Do dynamic names work?

Answer: 
```

Note that the dynamically named template is not loaded, regardless of extension.

## Additional Notes
At a glance the specification suggests the proper syntax for dynamic names is {{>*name}}, however the actual wording says `Dynamic Names consists of an asterisk, followed by a dotted name`. This wording suggests that the greater than sign is not intended to be part of the syntax.

When using `{{>*name}}` in mustache.java I get the following error:

```
Exception in thread "main" com.github.mustachejava.MustacheNotFoundException: Template *name.mustache not found
```

Note that this error is why I tried using `dn.mustache` in addition to `dn.template`, plus the fact that it feels weird that the specification would introduce a whole new extension just for this one use case.

When I use `{{*name}}` as the wording of the specification suggests, mustache.java does not throw an error, but no content is included in the output.

Thanks for taking a look!

**Comment by spullara** [comment]
This was optional for the specification, and no one has ever asked me for it before. It probably isn't a huge burden to implement it, let me take a stab at it. For reference, this is the official "spec":

https://github.com/mustache/spec/blob/master/specs/~dynamic-names.yml

**Comment by Hamilton-dfp** [comment]
That would be great.

I'll admit my use case requires a level of dynamism then what I would typically think mustache is suited for. However, mustache is easiest for me to execute on right now, and this feature is all that's missing to make this manageable.

Thank you for the official spec. It perfectly sums up the solutions I am hoping to avoid.

**Comment by spullara** [comment]
I have the change in a branch and will merge it shortly assuming no issues come up.

**Comment by spullara** [comment]
It is merged but it would great for you to test it if possible or propose a test case in a PR - right now it is passing the spec tests.

**Comment by Hamilton-dfp** [comment]
Thank you so much! Works just fine on my end.

Submitting a simple test for now:
https://github.com/spullara/mustache.java/pull/307

Getting ready to start some pretty gnarly use cases next. If I find anything that does not work I will submit more tests.

Thanks again!

**Comment by spullara** [comment]
Closing. If there is a bug that you find please open a new more specific issue. Thanks for helping make mustache.java more complete.

**Comment by Hamilton-dfp** [comment]
@spullara 

I've been using this feature pretty heavily and have not had any issues.

Could I request a release of 0.9.14 into maven central?

**Comment by spullara** [comment]
Sounds good. Will try and push it tomorrow.

**Comment by spullara** [comment]
0.9.14 was released but might take a bit to distribute from sonatype.

**Comment by Hamilton-dfp** [comment]
Confirmed that it is available. Thank you!
