### ISSUE TITLE
Comments are removed before TemplateFunction

### ISSUE THREAD

**Issue by smola** [spullara/mustache.java#89]
Comments are removed before TemplateFunction, even when TemplateFunction is supposed to be executed pre-substitution.

I apply a gettext-based i18n approach to my mustache templates, where I pass localizable strings to a i18n function (e.g. `{{#i}}This text is localizable{{/i}}`). This works great with `TemplateFunction` for pre-substitution templates. However, since comments are removed earlier, it's not possible to do `{{#i}}{{!verb}}Chat{{/i}}`, where `{{!verb}}` is some context that can be processed in my TemplateFunction while being inocuous for Mustache rendering.

Is there any chance that this can be changed or any workaround to be applied?

**Comment by spullara** [comment]
In master.

**Comment by spullara** [comment]
BTW, the other way to implement this is with a pragma, but I still like keeping the comments.
